apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pikaraoke
  namespace: pikaraoke
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.18.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    image:
      repository: vicwomg/pikaraoke
      tag: 1.23.0
      pullPolicy: IfNotPresent
    #Disable All Pods
    global:
      stopAll: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: localkaraoke.${DOMAIN_0}
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    service:
      main:
        enabled: true
        loadBalancerIP: "192.168.1.215"
        ports:
          main:
            port: 5555
            targetPort: 5555
        type: LoadBalancer
#    addons:
#      codeserver:
#        enabled: true
#        ingress:
#          enabled: true
#          ingressClassName: internal
#          hosts:
#            - host: cs-pikaraoke.${DOMAIN_0}
#          integrations:
#            certManager:
#              enabled: true
#              certificateIssuer: domain-0-le-prod

    persistence:
      data:
        enabled: true
        mountPath: "/app/pikaraoke-songs"

    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: false

    workload:
      main:
        podSpec:
#          runtimeClassName: "nvidia"
          containers:
            main:
              args:
              - "-u=https://localkaraoke.${DOMAIN_0}"
              - "-l=10"
#    resources:
#      limits:
#        cpu: 4000m
#        memory: 4800Mi
#        nvidia.com/gpu: 1