---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 24.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-arrs"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"

    metrics:
      main:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                RADARR__AUTH__METHOD: external
      exportarr:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: radarr.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: "Arr"
            widget:
              custom:
                key: "${HP_API_RADARR}"
    #    service:
    #      main:
    #        enabled: true
    #        loadBalancerIP: ""
    #        ports:
    #          main:
    #            port: 7878
    #        type: LoadBalancer
    persistence:
      config:
        volsync:
        - name: radarr-config
          type: restic
          credentials: backblaze
          dest:
            #VolSync Destination (Restore)
            enabled: true
          src:
            #VolSync Source (Backup)
            enabled: false
            trigger:
              schedule: 10 1 * * *
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media
        mountPath: /Media
        server: ${NAS_IP}
