---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: bazarr
spec:
  interval: 15m
  chart:
    spec:
      chart: bazarr
      version: 22.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    metrics:
      main:
        enabled: false
    #    workload:
    #      main:
    #        podSpec:
    #          containers:
    #            main:
    #              env:
    #                RADARR__AUTH__METHOD: external
    #      exportarr:
    #        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: bazarr.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: "Arr"
            widget:
              custom:
                key: "${HP_API_BAZARR}"
    #    service:
    #      main:
    #        enabled: true
    #        loadBalancerIP: ""
    #        ports:
    #          main:
    #            port: 7878
    #        type: LoadBalancer
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media
        mountPath: /Media
        server: ${NAS_IP}
