apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nostalgiatv
  namespace: nostalgiatv
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.23.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: true
    TZ: America/Los_Angeles
    image:
      repository: purestream711/nostalgiatv-server
      tag: 0.10.3@sha256:74644ec9a7305cbe8ba9371bf8ae67c79eb2f3db9b12b422a415d5edcc6a404f
      pullPolicy: IfNotPresent
    credentials:
      s3:
        type: s3
        url: ${S3_ENDPOINT_URL}
        bucket: "${S3_BUCKET}-NostalgiaTV"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: nostalgiatv.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    service:
      main:
        enabled: true
        ports:
          main:
            port: 19850
            targetPort: 19850
        type: ClusterIP

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsUser: 0
    workload:
      main:
        podSpec:
          runtimeClassName: "nvidia"
          containers:
            main:
              fixedEnv:
                PUID: 568
                GUID: 568
    persistence:
      config:
        enabled: true
        mountPath: "/app/config"
        volsync:
        - name: config
          type: restic
          credentials: s3
          dest:
            enabled: false
          src:
            enabled: false
            trigger:
              schedule: 30 0 * * *
      data:
        enabled: true
        mountPath: "/app/data"
        volsync:
        - name: data
          type: restic
          credentials: s3
          dest:
            enabled: false
          src:
            enabled: false
            trigger:
              schedule: 30 0 * * *
      logos:
        enabled: true
        mountPath: "/app/logos"
        volsync:
        - name: logos
          type: restic
          credentials: s3
          dest:
            enabled: false
          src:
            enabled: false
            trigger:
              schedule: 30 0 * * *
    resources:
      limits:
        nvidia.com/gpu: 1