apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/music-assistant/server
      tag: 2.4.3
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            allowCors: true
            enabled: true
          certManager:
          enabled: true
          certificateIssuer: domain-0-le-prod
        hosts:
        - host: jukebox.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
    service:
      main:
        enabled: true
        loadBalancerIP: ""
        ports:
          main:
            port: 8095
            targetPort: 8095
        type: LoadBalancer
    persistence:
      data:
        enabled: true
        mountPath: "/data"
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media/audio/music
        mountPath: /media/videovault
        server: ${NAS_IP}
    podOptions:
      hostNetwork: true
    securityContext:
      container:
        privileged: true
