apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.4.19
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/music-assistant/server
      tag: 2.5.8
      pullPolicy: IfNotPresent
    credentials:
      backblaze:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-musicassistant"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
        - host: "jukebox.${DOMAIN_0}"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          nginx:
            enabled: true
            auth:
              type: "authentik"
              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
              externalHost: "jukebox.${DOMAIN_0}"
          traefik:
            enabled: false
        #      snapcast:
        #        enabled: true
        #        ingressClassName: external
        #        hosts:
        #        - host: snapcast.${DOMAIN_0}
        #          paths:
        #          - path: /
        #            pathType: Prefix

        #            overrideService:
        #              name: snapcast
        #              port: 1780

        #        integrations:
        #          certManager:
        #            enabled: true
        #            certificateIssuer: domain-0-le-prod
        #          nginx:
        #            enabled: true
        #            auth:
        #              type: "authentik"
        #              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
        #              externalHost: "snapcast.${DOMAIN_0}"
    service:
      main:
        enabled: true
        loadBalancerIP: ""
        ports:
          main:
            port: 8095
            targetPort: 8095
        type: LoadBalancer

    #      snapcast:
    #        enabled: true
    #        loadBalancerIP: ""
    #        ports:
    #          snapcast:
    #            enabled: true
    #            port: 1780
    #            targetPort: 1780
    #        type: LoadBalancer
    persistence:
      data:
        enabled: true
        mountPath: "/data"
        volsync:
        - name: config
          type: restic
          credentials: backblaze
          dest:
            #VolSync Destination (Restore)
            enabled: false
          src:
            #VolSync Source (Backup)
            enabled: true
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media/audio/music
        mountPath: /media/music
        server: ${NAS_IP}
    podOptions:
      hostNetwork: true
    securityContext:
      container:
        privileged: true
