apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VX5KK/oIjnJNe8byxXZV7/I7Qn1/rmYVmTqq3taE9YRnHulrxDyiPLbYkV5RYmsjUB67dlWrSvg46ZQgjopU3KwM2tBnXhPzEjepUrUVvbRgqdx1vlhIPifR5t31rHmemdARa4uF/diK/kpTP7MTIp5GynW5M0N4KQb1JVyliS5n5tRUY1Po8omkUnSa8tcH3ex6ClqOKpU2JgwJwtbiSwDDkMNLM9P4JBwqxKY6fYHtNmF7NBSBm4wVCkiNYSDCgxubZ9CfT3nqdCZdVbjQwr7K8+qZ4fJGmtwNSTwm4tX+lfE2tijkiGLQS7PiyaaH1cQgphNnj3krV+eAEzkd18OTqihfP+olmFiLFV6YiS6pGp+B2kig96Vp/nRx7sny,iv:EZN+3DwBnhaOBoStQNAX/BgPRHWqpdYC8qBp8obT4ks=,tag:bD1JDcxd3hDco0Y/9K15mg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cgOAplpuQ8znKJjP+Kbgs3EbdOm4hcnQYhFuVInRrCzI5xaVjh7ie2OKikLGJsrXTXRQnrE8QTNcLOK7POTaqfKxAwHYO/2m0nYwIICipZDkuQVqQbuLPSJAIo4OO6Q4oqaM0aRaW7VtkhNcJFs5dYBpBJ3K1MA7APIH7dTaWdV+DA55geL6fVj3VEywkdpUX7ZxWBy582T1g1h8YFDF31q4ZBmu9fiUnM0Mkd62zs00WNXWbSKI1Qt40C1nnmOvwbmSSkFRsjKYbAuVgg==,iv:Cv0H3a1q3B7RbKhyLhgE1iXqWB4DmjiZFAdmECT1hcM=,tag:UxmqTW536PZG1GZDOVBPkg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kXC5T1wd47kGgRwYvEBRyUYSrPZt3YDcJUtpMopVrTLNNtrupKSQLe/679m1wE5WdtJuvKPnJS+s7QrF+wCQOyTZCGh5e0mm8+/LAOrf7ovR4rk5/HmFv5mItzCqQrzCVd/skyFcCe2N5wdhRh5Mbgl7i/NW/dYDQevlRTunJ2bhvbcbhGodeO5znZlhEqP5SVHgC+ywQgZF4valH5lVjmOdvRDVhYcoi8lI,iv:W57PK4/9FYoTr9rvF6INrEHZlPgex3cAnqnCexoTvQc=,tag:YUaAKJZi5RlQLwx4ctLvIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenl1NGxPNkRSZG42K2RW
            Vm1LOFY1dFBqUUlGVjNoNkNJaUhqVmtIa1hRCjhWOU9TUUJYbUtXek9EYkdpb0lD
            cllrTFdKOHJsL3ZOUUNjMjBKaW5qeDgKLS0tIDZZMExTdFl0aExWTW9rS2MwSVBR
            VjZlcEVNdFhDekVJMWxncW5WNko2Qm8KCcMRy+fsEPPUE1hdv0EC3LSIYCCzBceJ
            acaP8rJHZcamjxAOVGpSQNE+d0XvVBbNPrbErNJKBvNO2fcx7lK0Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T15:51:54Z"
    mac: ENC[AES256_GCM,data:CESCcyNYxQNRtsnw3CrBOErNT0UNOKIo0+/vhtNqo/AIQ7Ja1DtzDQNAB0xTnIRJbpQu6A/+W/Jlifa3tX867Y3Lu9t3mEiSxnb4ejuygYd1uFbDpbDWEQjTYWomOwZjptfuckqiGUrErL/wtr0VAUCmfJtVRgxPZtmPJD5U9R8=,iv:H3bhdQnwpEfYCbMuRpXI8LvopgvqEvoQTpO1EQQaww0=,tag:Knh5ANeDe6FgB86EHAD6/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
