apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qp6WaVWrF6sH4nQn4y/etlVKuqI5l/Lu1fLU4EfyjodHddxVZQFFs6K2A9BK8sjW9WsCQvVdfntjq93edeU45HpRAUZ3NETuvk7txHeM92RdunGHlgZIGIB8vj4lxiUSovhT3AhApVMmuoUkCLPBjlFrWxaXePzWWlBdvafLCjegicBNz8OcKQq+Q2uwgZX2IVmTHSB8V5mwR1tXz2yeFE3bEocUuSsA8EOQxOpK5IQE9WYEu1YQJWQoN0Nt9QO3t/6W2yQ5qjjrtHO44sPC+ChjluP3lA6ttJKVHn2IJMdO/Ai0MV1B5sbRCBxq++vqqFnI1QtXNrwDhDI0l460TODOh9IWR/m7fHIkb7TmFqsrVw94UM+GitM9wQSoWXwY,iv:WsIMKFMUOZkdfm+heyqjHyqnjXwiAqyVhGWkaWTfakU=,tag:m0wqgbSZYDCoHFsW2dKbAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:d8Dq7CoiilUjN8W4f1c2ElTBPi9caQJuz9ERyp8H0u9el9gMBPLOYgL43uQFwXQsFyv/mUIYxzRjSBh5+O9dad49vTs9C4dKUH8c90610HKLs7gvvxFkCgowBk2l7ZsDae5hqQIAEQgz2ZPBoV1OkDMVTFHq2Jzw3S59QcpQCjM1wtXqVeJbxk9Snewrob+lPI4/1OaQQ9AAk9MVKbLw/EtJATsKEOUPGOkQ4TCCfOtTN5mbZyo3ysu+LTUD5WAkYwbI7xytoc2epeOihw==,iv:zutLjX8cKksbwALHofYyd4+w/RXvfDCyfpWo9NBv/lM=,tag:4eIyjrNjtz5ClVaFSWSSWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:HpjRqttSSre1jF44gxiBH5jJ0tUoZcqAGmdsxF5cNSdV1gHvKm4/4gzK+7ruHog3RAMtbod0n2O8LicaMwtZMFJy9mQTMa1YXYEwc6+HD3EbMbXsCYW0GgxqxBYK8LhyG2olZHKgFIn+IIUhhQP1oAzAnbwzj3YKToSaDpT7p5dnNJ0Vv6jrDqJGi64PWN7ACGwpBc9j1qGCz602yCrzqHOOrl8B+owmMpeJ,iv:jF+FMorFMhXjTLdMAsO7u/++tIfQLKEoXhxQ9V5pl34=,tag:F0a67uo7SPRphnmYTFRX/w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cFRXdWplclFya2dPZjNx
            d2p5eEFoMkhqTWhweFlMa1oxWmRJT29JTGlNCi9Rc2N5a01GT0hHS2JvV2VObEc2
            a3RpcXhEMDI5dUJ4Rzc2UGZwcGtSencKLS0tIDE2cmlCVm44VzdvTE5wWUU4M3U0
            YnN6YWNOUXFLWFNLM0VidnIzVGhMQWcKSck5qY6ITbFncSZ89Baz4QbnZ2tp0nz8
            kq0msCsEK3ZG6tE3WPXUWHIAJyJvprnHChQAfqdbFzVwFgyAJfi/MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-10T20:04:20Z"
    mac: ENC[AES256_GCM,data:SnhWpcrwD/Jbqba7dx7i+f+KvWtZk8JK7gUxg4t34laYU2jmn0GlNjYpaTylcudDt78UW4tjhuShhdF4pDjU360r0jzpfmwhPEnIuJS1Zg7g0BkEpKT7rMN0SDoGWSMJ/1jVJ8aHWtjpmYNfOUQZRl/9CZ1b9csqW2krmZjwNVI=,iv:Iel7JyhARDtg8GWRIW2lHLXejnc1cR4zGwpTtc1l90Q=,tag:QaDxfFQgrfjozXvR8vUEeg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
