apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uuWNBf2Ssx2Cpk4HmS+FfaC9Fcaa2VlMMQm6wA6YqVOkzuutOYJs/ehBm7quD+tuRs5JlEF7W3SHi41vsbnBYT8Pss3/PoDE4sklEehw25vLMNufDSradG6TorL5LccJ7wtmg4AGYbLxF0nfnEF8jyOtrLo1e0o1P6cer5bAl/biblfG5AJ0C7RCJLq8UMKdVTDikGWClRSMScRjBsnqdw3JIXpGe2NyRwhHDepScdikWmtmIISAm+mCEN+Sr77elJIBq/xMLCORrZbGYEL/JqLdPH2yWDZ9e7MSPR/WtWZeNrayURwUr0OshO7INZWUCX6VWsDVOXa3UEsogecvFRo55xwj5jx++IDnaWIWUkKw6gmzM35f8ybO465pfe8o,iv:87z3RkI4/axyO8ftK7xX/3USOyqASsl0Y0QaHrfLsDo=,tag:K0oPqFox5YS4qrYSnAo/Gg==,type:str]
    identity.pub: ENC[AES256_GCM,data:zsqIll2e2m4E8FBe0SIj+AWRrxx3Kixz+wup/AKHS1U4TZrNRedKQpQa/rx3feqGQr2So8abRcI2WxnZeVoB1iMlJc3u3KsAotlq05XSndyl+c7aq7xMpygg7l1wAYbTzxohVIbgmDUjCbWEu0sJLhU9iIH89APcXprP3Npz88lFFoFSQ/EvbgkkZnF7Bxki7HLIjK3ltS0Iu4vzkeqqrSDNDuzN5S65hpoZhKJrlqBP31pQzwOFf8iwqFY5xkSvELWKBv51hJsd5xY5Dg==,iv:QtnsltyMeqFwHr5MUvZzKbJtGrxKcbWE2aBllwTE3jk=,tag:G0dP9/DLW/Cdu7uvOTu1PQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:529CrkL+RMCS/Owp539JL+dbmyj3/L6SoCnb8Cr1ClZOXC+IpzvuRJu7yOZLqgbOK9yaN+Aurab5zMYNfuJ87OPApNdNh0H1TGobRQgpV9yn2sixQbzAA7WL5rFLsT9H9olzbqYs00TekIwP7zsr3IDzVH7yqzp5ol2aqFYvOHEjJ6feyMIUKFVSQuXq1RU8yn0Mk3lSO+qQ/tWAi3RVQg9RETddokZ4cgIg,iv:D34dwnnBYB5cHD5iNKqcflElFkJe46Mm/He8ji81SzQ=,tag:I1keoez0oPgvIyPnRMWNsA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNzdkbEt3KzUwc3h4VGVJ
            WVpVazI3KzVlREVVTFlIai9wSk1WUzk5U2lFCnFIYnZ5OHRTbXhadnZhNDgwemgr
            TnFwcHJqa0pRcGxqRjU0Ynl0TUZPWFEKLS0tIEVlZmF6NXVpTlpkNGlBSndRSlBM
            dVZIR0trRG5tclRzazd5SGs2YnFkcjQKPvW+Gjs05vf/AYmU5L1CgXgZdeZRN/wo
            1d0e/+SKGMDo/BFoiuVWFD9uBEFWJqodQoADiU8D7FLR+xWiE1zUBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyuw80hxtzf6v9szfzkn0pwyhtdushp0t4lr2hel06prfkxtcu0s4rac88
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-06T17:45:33Z"
    mac: ENC[AES256_GCM,data:g9WsNJQYdF5FBcS4ZpRlCBkYeWtXTH1hUUeFfnNczgakUMfEMS36J/xQG3FJgeaXD0EqolhRZSgRknFWlKK0iB02aGJaCdTF2onyQUnIVcbOvTBZu5SINIGVS0eBp+cHcnwKOiWKA/OaxEVQE7vuZa7umvPqKjulmDEROsHfOjg=,iv:2yQoIj6Wk4heikdLNBvUX2O7LGkC5+dMFil8dzqik7Q=,tag:3PIg/NoFIF7Gp6RvqD0Ang==,type:str]
    shamir_threshold: 3
    version: 3.13.1
