apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: homepage
      version: 9.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      backblaze:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-homepage"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            #entrypoints:
            #- websecure
        tls:
        - hosts:
          - home.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
        hosts:
        - host: home.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
                #entrypoints:
                #- websecure
          tls:
          - hosts:
            - homepage.code${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
          hosts:
          - host: homepage.code.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: backblaze
          dest:
            enabled: false
          src:
            enabled: true
            trigger:
              schedule: 10 0 * * *
