---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valheim
  namespace: valheim
spec:
  interval: 15m
  chart:
    spec:
      chart: valheim
      version: 13.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        integrations:
          metallb:
            enabled: true
        loadBalancerIP: ""
      valheim:
        integrations:
          metallb:
            enabled: true
        loadBalancerIP: "${VALHEIM_IP}"
    ingress:
      supervisor:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: valheim.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-pro
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_NAME: Drathros Kingdom
                WORLD_NAME: HeimHeimlich
                SERVER_PUBLIC: false
                UPDATE_INTERVAL: 10800
                BACKUPS: true
                BACKUPS_INTERVAL: 43200
                BACKUPS_DIRECTORY: /backups
                BACKUPS_MAX_AGE: 3
                SUPERVISOR_HTTP_USER: ${VALHEIM_ADMIN}
                SUPERVISOR_HTTP_PASS: ${VALHEIM_ADMIN_PASS}
                SERVER_PASS: ${VALHEIM_SERVER_PASS}
