---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 18.20.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false

    credentials:
      backblaze:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-arrs"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PROWLARR__AUTH__METHOD: external
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            #entrypoints:
            #- websecure
          homepage:
            enabled: true
            group: "Arr"
            widget:
              custom:
                key: "${HP_API_PROWLARR}"
        tls:
        - hosts:
          - prowlarr.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
        hosts:
        - host: prowlarr.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix

    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: backblaze
          dest:
            #VolSync Destination (Restore)
            enabled: false
          src:
            #VolSync Source (Backup)
            enabled: true

#    service:
#      main:
#          enabled: true
#          loadBalancerIP: ""
#          ports:
#              main:
#                  port: 9696
#          type: LoadBalancer
