apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: jellyseerr
      version: 13.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT_URL}"
        bucket: "${S3_BUCKET}-jellyseerr"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
        - host: mediareq.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: "Media"
            widget:
              custom:
                key: "${HP_API_JELLYSEERR}"
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: s3
          dest:
            enabled: false
          src:
            enabled: true
            trigger:
              schedule: 30 23 * * *
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media/VideoVault
        mountPath: /media/videovault
        server: ${NAS_IP}

#      resources:
#        limits:
#          nvidia.com/gpu: 1
#      workload:
#        main:
#          podSpec:
#            runtimeClassName: "nvidia"
