---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 16.17.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    metrics:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
        - hosts:
          - calserv.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
        hosts:
        - host: calserv.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
      webserver:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
        - hosts:
          - calibreserv.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
        hosts:
        - host: calibreserv.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
    #    service:
    #      main:
    #        enabled: true
    #        loadBalancerIP: ""
    #        ports:
    #          main:
    #            port: 7878
    #        type: LoadBalancer
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/Ottvault/Media
        mountPath: /Media
        server: ${NAS_IP}
