apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudflareddns
    namespace: cloudflareddns
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: cloudflareddns
            version: 11.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        cloudflareddns:
            #user: ${DOMAIN_0_EMAIL}
            api_token: ${CLOUDFLARE_DDNS_TOKEN}
            detect_mode: dig-whoami.cloudflare
            host_zone_record:
              - domain: ${DOMAIN_0}
                record: A
                zone: ${ZONE_0}
            interval: 300
            log_level: 3
