apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: searxng
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: true
    credentials:
      s3:
        type: s3
        url: ${S3_ENDPOINT_URL}
        bucket: "${S3_BUCKET}-ntfy"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: searx.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: s3
          dest:
            enabled: false
          src:
            enabled: true
            trigger:
              schedule: 30 0 * * *
#    addons:
#      codeserver:
#        enabled: false
#        ingress:
#          enabled: true
#          ingressClassName: internal
#          hosts:
#          - host: searxcode.${DOMAIN_0}
#          integrations:
#            nginx:
#              enabled: true
#            certManager:
#              enabled: true
#              certificateIssuer: domain-0-le-prod
