---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}

    middlewares:
      forwardAuth:
      - address: http://authentik-http.authentik.svc.cluster.local:10230/outpost.goauthentik.io/auth/traefik
        authRequestHeaders: []
        authResponseHeaders:
        - authorization
        - x-authentik-username
        - x-authentik-groups
        - x-authentik-email
        - x-authentik-name
        - x-authentik-uid
        - x-authentik-jwt
        - x-authentik-meta-jwk
        - x-authentik-meta-outpost
        - x-authentik-meta-provider
        - x-authentik-meta-app
        - x-authentik-meta-version
        authResponseHeadersRegex: ""
        name: auth
        tls:
          insecureSkipVerify: true
        trustForwardHeader: true
      geoBlock:
      - allowLocalRequests: true
        allowUnknownCountries: false
        api: https://get.geojs.io/v1/ip/country/{ip}
        apiTimeoutMs: 500
        blackListMode: false
        cacheSize: 25
        countries:
        - US
        - CA
        forceMonthlyUpdate: true
        logAllowedRequests: false
        logApiRequests: false
        logLocalRequests: false
        name: geoip
        unknownCountryApiResponse: nil
